mes = int(input("entre com um número de 1 - 12: "))

if mes == 1 : print('\njaneiro\n')
elif mes == 2 : print('\nfevereiro\n')
elif mes == 3 : print('\nmarço\n')
elif mes == 4 : print('\nabril\n')
elif mes == 5 : print('\nmaio\n')
elif mes == 6 : print('\njunho\n')
elif mes == 7 : print('\njulho\n')
elif mes == 8 : print('\nagosto\n')
elif mes == 9 : print('\nsetembro\n')
elif mes == 10 : print('\noutubro\n')
elif mes == 11 : print('\nnovembro\n')
elif mes == 12 : print('\ndezembro\n')
else : print('INVÁLIDO')